/**
 * Lucide React icon wrapper. Maps Font Awesome–style names to Lucide icons.
 * Usage: <Icon name="chart-line" className="..." size={20} />
 * Names can be "fa-xxx" or "xxx" (fa-solid/fa-regular/fa-brands stripped).
 */
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BarChart2,
  Bell,
  Building,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardList,
  Clock,
  CloudOff,
  Coins,
  Copy,
  CreditCard,
  Crown,
  Database,
  Download,
  DoorOpen,
  Droplet,
  EyeOff,
  File,
  FileText,
  Filter,
  FilterX,
  Flame,
  FolderOpen,
  Footprints,
  Globe,
  Hash,
  Heart,
  Home,
  Image,
  Images,
  Inbox,
  IndianRupee,
  Info,
  Key,
  LayoutGrid,
  Leaf,
  LineChart,
  List,
  ListChecks,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Minimize2,
  Minus,
  Package,
  Palette,
  Pencil,
  Phone,
  PieChart,
  Plus,
  RotateCcw,
  RotateCw,
  Save,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Soup,
  Sparkles,
  Star,
  Store,
  Table,
  Tag,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  Type,
  Upload,
  UploadCloud,
  User,
  Users,
  UtensilsCrossed,
  X,
  Sun,
  Moon,
  ToggleRight,
  Banknote,
  Wifi,
} from 'lucide-react';

const ICON_MAP = {
  'chart-line': TrendingUp,
  'rupee-sign': IndianRupee,
  'indian-rupee-sign': IndianRupee,
  'shopping-cart': ShoppingCart,
  'exclamation-triangle': TriangleAlert,
  'triangle-exclamation': TriangleAlert,
  users: Users,
  'chart-bar': BarChart2,
  'clock-rotate-left': RotateCcw,
  images: Images,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  check: Check,
  xmark: X,
  times: X,
  whatsapp: MessageCircle,
  'location-dot': MapPin,
  truck: Truck,
  walking: Footprints,
  gate: DoorOpen,
  plus: Plus,
  'info-circle': Info,
  minus: Minus,
  'check-circle': CheckCircle,
  'clipboard-list': ClipboardList,
  'calendar-day': CalendarDays,
  hashtag: Hash,
  calendar: Calendar,
  'calendar-alt': Calendar,
  'calendar-week': Calendar,
  clock: Clock,
  trash: Trash2,
  phone: Phone,
  'shield-halved': Shield,
  'shield-check': ShieldCheck,
  envelope: Mail,
  lock: Lock,
  spinner: Loader2,
  'arrow-right-to-bracket': LogIn,
  key: Key,
  cog: Settings,
  'sign-out-alt': LogOut,
  bell: Bell,
  database: Database,
  user: User,
  palette: Palette,
  building: Building,
  store: Store,
  bullhorn: Megaphone,
  save: Save,
  tag: Tag,
  sun: Sun,
  moon: Moon,
  box: Package,
  'toggle-on': ToggleRight,
  'calendar-check': CalendarCheck,
  'list-check': ListChecks,
  magic: Sparkles,
  copy: Copy,
  message: MessageSquare,
  'money-bill-wave': Banknote,
  font: Type,
  'text-height': Type,
  'eye-slash': EyeOff,
  'cloud-upload-alt': UploadCloud,
  'folder-open': FolderOpen,
  file: File,
  'window-minimize': Minimize2,
  'arrow-down': ArrowDown,
  'window-maximize': Maximize2,
  download: Download,
  upload: Upload,
  coins: Coins,
  pencil: Pencil,
  crown: Crown,
  star: Star,
  table: Table,
  th: LayoutGrid,
  list: List,
  inbox: Inbox,
  circle: Circle,
  'arrow-up': ArrowUp,
  'arrow-right': ArrowRight,
  utensils: UtensilsCrossed,
  'file-alt': FileText,
  'chart-pie': PieChart,
  'times-circle': X,
  'circle-check': CheckCircle,
  filter: Filter,
  'filter-circle-xmark': FilterX,
  'credit-card': CreditCard,
  'chart-area': LineChart,
  image: Image,
  wifi: Wifi,
  'cloud-exclamation': CloudOff,
  leaf: Leaf,
  house: Home,
  home: Home,
  droplet: Droplet,
  'truck-fast': Truck,
  fire: Flame,
  heart: Heart,
  globe: Globe,
  'circle-check': CheckCircle,
  'circle-exclamation': TriangleAlert,
  'circle-info': Info,
  'exclamation-circle': TriangleAlert,
  'bowl-rice': Soup,
  'bread-slice': UtensilsCrossed,
  'person-walking': Footprints,
  'toggle-off': ToggleRight,
  bars: Menu,
  rotate: RotateCw,
};

function getIconComponent(name) {
  if (!name || typeof name !== 'string') return null;
  const key = name
    .replace(/^fa-(solid|regular|brands)\s+/, '')
    .replace(/^fa-/, '')
    .trim();
  return ICON_MAP[key] || null;
}

export default function Icon({ name, className = '', size = 20, spin = false, ...props }) {
  const Component = getIconComponent(name);
  if (!Component) return null;
  const isLoader = name === 'spinner' || String(name).includes('spinner');
  const spinClass = (spin || isLoader) ? 'lucide-icon-spin' : '';
  return (
    <Component
      size={size}
      className={`lucide-icon ${spinClass} ${className}`.trim()}
      aria-hidden
      {...props}
    />
  );
}

export { getIconComponent, ICON_MAP };
