// Script to add a test order to the database
import dotenv from "dotenv";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import mongoose from "mongoose";
import Order from "../models/Order.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load environment variables
dotenv.config({ path: join(__dirname, "../../../.env") });
dotenv.config({ path: join(__dirname, "../../.env") });
dotenv.config();

// Connect to MongoDB
const connectDB = async () => {
  try {
    const mongoURI =
      process.env.MONGOURI || process.env.MONGODB_URI || process.env.MONGO_URI;
    if (!mongoURI) {
      console.error(
        "❌ Error: MONGOURI, MONGODB_URI, or MONGO_URI not found in environment variables",
      );
      console.error(
        "💡 Tip: Make sure .env file exists in backend/ or root directory",
      );
      console.error(
        "💡 Or set MONGOURI environment variable before running this script",
      );
      process.exit(1);
    }
    await mongoose.connect(mongoURI);
    console.log("✅ Connected to MongoDB");
  } catch (error) {
    console.error("❌ MongoDB connection error:", error.message);
    process.exit(1);
  }
};

// Add test order
const addTestOrder = async () => {
  try {
    await connectDB();

    // Create a test order matching the example from the image
    // Date: 5-Feb-24, Address: A3-1206, Quantity: 2, Unit Price: 100, Total: 200
    const testDate = new Date("2024-02-05");
    testDate.setHours(12, 0, 0, 0); // Set to noon for consistency

    const testOrder = new Order({
      date: testDate,
      deliveryAddress: "A3-1206",
      customerName: "Test Customer",
      quantity: 2,
      unitPrice: 100,
      // totalAmount will be auto-calculated (quantity * unitPrice = 200)
      paymentStatus: "Paid",
      paymentMode: "Online",
      mode: "Lunch",
      status: "Paid", // Legacy field
      source: "manual",
      notes: "Test order created by script - matches example data",
    });

    // Save the order (orderId will be auto-generated by pre-validate hook)
    const savedOrder = await testOrder.save();

    console.log("\n✅ Test order created successfully!");
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.log("Order Details:");
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.log(`Order ID:     ${savedOrder.orderId}`);
    console.log(
      `Date:         ${savedOrder.date.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}`,
    );
    console.log(`Address:      ${savedOrder.deliveryAddress}`);
    console.log(`Customer:     ${savedOrder.customerName}`);
    console.log(`Quantity:     ${savedOrder.quantity}`);
    console.log(`Unit Price:   ₹${savedOrder.unitPrice}`);
    console.log(`Total Amount: ₹${savedOrder.totalAmount}`);
    console.log(`Mode:         ${savedOrder.mode}`);
    console.log(`Status:       ${savedOrder.paymentStatus}`);
    console.log(`Payment Mode: ${savedOrder.paymentMode}`);
    console.log(`Billing Month: ${savedOrder.billingMonth}`);
    console.log(`Billing Year:  ${savedOrder.billingYear}`);
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");

    // Close connection
    await mongoose.connection.close();
    console.log("✅ Database connection closed");
    process.exit(0);
  } catch (error) {
    console.error("\n❌ Error creating test order:", error.message);
    if (error.code === 11000) {
      console.error(
        "⚠️  Duplicate order detected. Order ID might already exist.",
      );
    }
    await mongoose.connection.close();
    process.exit(1);
  }
};

// Run the script
addTestOrder();
